# Custom Language File for Launcher Customizer

[ejs.app]
title = "포켓빌"

[ejs.landing]
mediaGitHubURL = "https://cafe.naver.com/reademinecraft"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = ""
mediaSoopURL = "#"
mediaChzzkURL = "https://chzzk.naver.com/77172c972f3db828c970e9b63a40ae21"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/mchlauncher/PokeVill"
supportLink = "https://github.com/mchlauncher/PokeVill/issues"

[ejs.welcome]
welcomeHeader = "포켓빌"
welcomeDescription = ""
welcomeDescCTA = "[계속] 버튼을 눌러 계속 진행하여 주세요."