# Custom Language File for Launcher Customizer

[ejs.app]
title = "포켓빌_ST"

[ejs.landing]
mediaGitHubURL = "https://cafe.naver.com/reademinecraft"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = ""
mediaSoopURL = "#"
mediaChzzkURL = "https://chzzk.naver.com/1197ac8b30f9b98bb04b1a1394781daf"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/mchlauncher/PokeVill"
supportLink = "https://github.com/mchlauncher/PokeVill/issues"

[ejs.welcome]
welcomeHeader = "포켓빌_ST"
welcomeDescription = ""
welcomeDescCTA = "[계속] 버튼을 눌러 계속 진행하여 주세요."